[package]
name = "quant-common"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
chrono = { workspace = true }
uuid = { workspace = true }
rust_decimal = { workspace = true, features = ["maths"] }
thiserror = { workspace = true }
anyhow = { workspace = true }
tracing = { workspace = true }
sqlx = { workspace = true, optional = true }
redis = { workspace = true, optional = true }
reqwest = { workspace = true, optional = true }
okx = { workspace = true }
quant-domain = { path = "../domain" }
[dev-dependencies]
rust_decimal_macros = "1.36"

[features]
default = []
db = ["sqlx", "redis", "reqwest"]
