[package]
name = "data-puller"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true

[dependencies]
quant-common = { path = "../common" }
exchange-binance = { path = "../exchange-binance" }
data-layer = { path = "../data-layer" }

tokio = { workspace = true }
chrono = { workspace = true }
rust_decimal = { workspace = true }
async-trait = "0.1"
serde_json = { workspace = true }
tracing = { workspace = true }

[lints]
workspace = true
